# Generated by Django 3.1.1 on 2020-09-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Catogery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.catogery'),
            preserve_default=False,
        ),
    ]
