# Generated by Django 3.1.1 on 2020-09-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='img',
        ),
    ]
