# Generated by Django 3.1.1 on 2020-09-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
